#ifndef GUARD_CONSTANTS_ACHIEVEMENTS_H
#define GUARD_CONSTANTS_ACHIEVEMENTS_H

enum {
    ACHIEVEMENT_WIN_WAH_CHALLENGE = 0,
    ACHIEVEMENT_DEFEAT_ALL_ADMINS,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_5_TIMES,
    ACHIEVEMENT_LOSE_50_TIMES,
    ACHIEVEMENT_DEFEAT_ALL_COLLABORATORS,
    ACHIEVEMENT_COUNT,
};

#endif // GUARD_CONSTANTS_ACHIEVEMENTS_H
