#ifndef GUARD_CONSTANTS_ACHIEVEMENTS_H
#define GUARD_CONSTANTS_ACHIEVEMENTS_H

enum {
    ACHIEVEMENT_WIN_WAH_CHALLENGE = 0,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_DOUBLE,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_RANDOM,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_INVERSE,
    ACHIEVEMENT_DEFEAT_ALL_ADMINS,
    ACHIEVEMENT_DEFEAT_ALL_COLLABORATORS,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_5_TIMES,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_10_TIMES,
    ACHIEVEMENT_WIN_WAH_EACH_MODE_TWICE,
    ACHIEVEMENT_DEFEAT_WAH_CHALLENGE_HARD_MODE,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_WITH_ELECTRODES,
    UNLOCK_ALL_POKEMON,
    ACHIEVEMENT_COUNT,
};

#endif // GUARD_CONSTANTS_ACHIEVEMENTS_H
