#ifndef GUARD_CONSTANTS_ACHIEVEMENTS_H
#define GUARD_CONSTANTS_ACHIEVEMENTS_H

enum {
    ACHIEVEMENT_WIN_WAH_CHALLENGE = 0,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_STANDARD,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_DOUBLE,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_RANDOM,
    ACHIEVEMENT_DEFEAT_ALL_ADMINS,
    ACHIEVEMENT_WIN_WAH_CHALLENGE_5_TIMES,
    ACHIEVEMENT_DEFEAT_ALL_COLLABORATORS,
    ACHIEVEMENT_DEFEAT_WAH_CHALLENGE_HARD_MODE,
    UNLOCK_ALL_POKEMON,
    ACHIEVEMENT_COUNT,
};

#endif // GUARD_CONSTANTS_ACHIEVEMENTS_H
