#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_JACK_JOHNSON,
    SP_NAME_GOCE,
    SP_NAME_REONEKY,
    SP_NAME_REY_BOO,
    SP_NAME_CHEVE,
    SP_NAME_BARO,
    SP_NAME_JAVI4315,
    SP_NAME_JAVS,
    SP_NAME_GALLEGO,
    SP_NAME_SERGIO,
    SP_NAME_TOKYN,
    SP_NAME_WAR,
    SP_NAME_OMEGA,
    SP_NAME_OZUMAS,
    SP_NAME_SCAREX,
    SP_NAME_ANGEL,
    SP_NAME_KATHERINE,
    SP_NAME_DRIVE,
    SP_NAME_XIROS,
    SP_NAME_COSARARA,
    SP_NAME_UNKNOWN,
    SP_NAME_PKPOWER,
    SP_NAME_KLEIN,
    SP_NAME_AGUIAR,
    SP_NAME_ROXAS,
    SP_NAME_INMORTAL_KAKTUS,
    SP_NAME_GAMEBOY_CL,
    SP_NAME_ERKEY,
    SP_NAME_MICOLO,
    SP_NAME_COPE,
    SP_NAME_MRNIGHTOLOGY,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
