
#ifndef GUARD_CONSTANTS_VAR_VALUES_H
#define GUARD_CONSTANTS_VAR_VALUES_H

#define VAR_VALUE_WAH_CHALLENGE_MODE_NONE 0
#define VAR_VALUE_WAH_CHALLENGE_MODE_STANDARD 1
#define VAR_VALUE_WAH_CHALLENGE_MODE_DOUBLE 2
#define VAR_VALUE_WAH_CHALLENGE_MODE_INVERSE 3

#define BETA_MON_QUESTION_GOROCHU 0
#define BETA_MON_QUESTION_TAABAN 1
#define BETA_MON_QUESTION_BOMUSHIKAA 2
#define BETA_MON_QUESTION_MADAAMU 3
#define BETA_MON_QUESTION_AKUERIA 4
#define BETA_MON_QUESTION_LATIKEN 5

#define BETA_MON_QUESTION_PICK_QUESTION 0
#define BETA_MON_QUESTION_PICK_NO_CREDIT 1
#define BETA_MON_QUESTION_PICK_ALL_UNLOCKED 2
#define BETA_MON_QUESTION_PICK_NONE_THIS_TALK 3

#endif // GUARD_CONSTANTS_VAR_VALUES_H
