
#ifndef GUARD_CONSTANTS_VAR_VALUES_H
#define GUARD_CONSTANTS_VAR_VALUES_H

#define VAR_VALUE_WAH_CHALLENGE_MODE_NONE 0
#define VAR_VALUE_WAH_CHALLENGE_MODE_STANDARD 1
#define VAR_VALUE_WAH_CHALLENGE_MODE_DOUBLE 2

#endif // GUARD_CONSTANTS_VAR_VALUES_H
