#ifndef GUARD_CONSTANTS_WAH_TEAM_INDEXES_H
#define GUARD_CONSTANTS_WAH_TEAM_INDEXES_H

enum WahTeamIndexes {
    TEAM_INDEX_CHEVE = 0,
    TEAM_INDEX_OMEGA = 1,
    TEAM_INDEX_GOCE = 2,
    TEAM_INDEX_BLAX = 3,
    TEAM_INDEX_SAYER = 4,
    TEAM_INDEX_AGUIAR = 5,
    TEAM_INDEX_JACK_JOHNSON = 6,
    TEAM_INDEX_ANGEL = 7,
    TEAM_INDEX_OZUMAS = 8,
    TEAM_INDEX_SCAREX = 9,
    TEAM_INDEX_DAVZERO = 10,
    TEAM_INDEX_BARO = 11,
    TEAM_INDEX_REYBOO = 12,
    TEAM_INDEX_COSARARA = 13,
    TEAM_INDEX_DRIVE = 14,
    TEAM_INDEX_KATHERINE = 15,
    TEAM_INDEX_REONEKY = 16,
    TEAM_INDEX_GALLEGO = 17,
    TEAM_INDEX_EING = 18,
    TEAM_INDEX_TOKYN = 19,
    TEAM_INDEX_WAR = 20,
    TEAM_INDEX_JAVI4315 = 21,
    TEAM_INDEX_JAVS = 22,
    TEAM_INDEX_SERGIO = 23,
    TEAM_INDEX_XIROS = 24,
    TEAM_INDEX_KLEIN = 25,
    TEAM_INDEX_PKPOWER = 26,
};

#endif // GUARD_CONSTANTS_WAH_TEAM_INDEXES_H