gText_GirlOrBoy::
	.string "Are you a girl or a boy?$"

gText_SoItsPlayer::
	.string "So you're {PLAYER}?$"

gText_Cope_YesNo::
	.string "▶Yes\n{CLEAR_TO 8}No$"

gText_Cope_NoYes::
	.string "{CLEAR_TO 8}Yes\n▶No$"

gText_Choose_Difficulty::
	.string "Select the Difficulty$"

gText_Cope_Easy::
	.string "Easy$"

gText_Cope_Normal::
	.string "Normal$"

gText_Cope_Hard::
	.string "Hard$"

gText_Difficulty_CharacteristicsHeader::
	.string "Features:$"

gText_Easy_Description::
	.string "· Basic AI\n"
	.string "· Easier teams\n"
	.string "· Rivals with 0 EVs and IVs\n"
	.string "· Rivals don't use healing\nitems$"

gText_Normal_Description::
	.string "· Smart AI\n"
	.string "· Challenging matches\n"
	.string "· Competitive stats\n"
	.string "· Rivals use items$"

gText_Hard_Description::
	.string "· Smart AI\n"
	.string "· Battle style: Set\n"
	.string "· Competitive stats\n"
	.string "· Tougher teams\n"
	.string "· Rivals use more items$"

gText_Cope_Welcome::
	.string "Ah... great.\n"
	.string "Another trainer itching to get\l"
	.string "banned.\p"
	.string "My name's Cope, but I also go\n" 
	.string "by Zunex, Zel!x, Patrick...\p" 
	.string "(...){PAUSE 0x24}(...){PAUSE 0x24}(...){PAUSE 0x24}\p"
	.string "Still don't know me...? Then\n"
	.string "you probably know me from some\l"
	.string "public tiles, right?\p"
	.string "All right, let's get to the point.\p"
	.string "The challenge is simple: each floor\n"
	.string "has a room with an admin\l"
	.string "dying to ban you out of existence.\p"
	.string "And no, there are no bugs, no tricks, no\n"
	.string "misplaced invisible tiles... I think.\p"
	.string "Isn't that great?\p"
	.string "(...){PAUSE 0x24}(...){PAUSE 0x24}(...){PAUSE 0x24}\p"
	.string "And speaking of great things..."
	.string "$"

gText_Cope_Pokemon::
	.string "Meet Tile, my loyal partner.\p"
	.string "The two of us work just\n"
	.string "like a sprite with its palette.\p"
	.string "With our colors in harmony and no\n"
	.string "jaggies in sight, nobody can\l"
	.string "stop us."
	.string "$"

gText_Cope_ExplainChalenge::
	.string "That's exactly what you'll have to do.\p"
	.string "(...)(...)(...)\p"
	.string "Don't look at me like that! Relax, you\n"
	.string "won't need to memorize any offsets.\p"
	.string "It's dead simple: you'll be handed a\n"
	.string "team, and you'll have to reach the\l"
	.string "top with it.\p"
	.string "Get past the bugs and jaggies\n"
	.string "that pop up along the way.\p"
	.string "If you make it, the door to the\n"
	.string "next room will open.\l"
	.string "Promise.\p"
	.string "Now that you know the deal...\n"
	.string "Choose your Pokémon team!{PAUSE_UNTIL_PRESS}$"

	

gText_Cope_Farewell::
	.string "Good choice!\n"
	.string "All I can do is wish you luck.\p"
	.string "I hope you put on a good show\n"
	.string "and reach the top. And trust me,\l"
	.string "not even the folks beyond the grave\l"
	.string "would miss this challenge.\p"
	.string "If not... well, you can always blame\n"
	.string "the RNG.\p"
	.string "Come on, this tower isn't going to\n"
	.string "climb itself!$"

gText_Birch_AndYouAre::
	.string "And who are you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy or a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "And what's your name?$"

gText_Birch_SoItsPlayer::
	.string "So you're {PLAYER}{KUN}…$"

gText_Birch_YourePlayer::
	.string "Ah, yes, now I remember!\p"
	.string "You just moved to my\n"
	.string "hometown, LITTLEROOT.\l"
	.string "Right?\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Okay, listen closely to what\n"
	.string "I'm about to tell you…\p"
	.string "Your very own adventure is about\n"
	.string "to begin.\p"
	.string "Go on, step into the world of\n"
	.string "POKéMON: a dreamlike world full\l"
	.string "of adventure and great friends.\p"
	.string "Well, come see me later. I'll be waiting\n"
	.string "at my POKéMON LAB.\p"
	.string "$"
