gText_Cope_Welcome::
	.string "Ah... genial.\n"
	.string "Otro entrenador con ganas de ser\l"
	.string "baneado.\p"
	.string "Mi nombre es Cope, pero también me\n" 
	.string "conocen como Zunex, Zel!x, Patrick...\p" 
	.string "(...){PAUSE 0x24}(...){PAUSE 0x24}(...){PAUSE 0x24}\p"
	.string "¿Sigues sin conocerme...? Entonces\n"
	.string "seguramente me reconozcas por algunos\l"
	.string "tiles públicos, ¿verdad?\p"
	.string "Muy bien, vamos al grano.\p"
	.string "El desafío es simple: cada piso\n"
	.string "tiene una sala donde habrá un admin\l"
	.string "con ganas de banearte la existencia.\p"
	.string "Y no, no hay bugs, ni trucos, ni tiles\n"
	.string "invisibles mal puestos... creo.\p"
	.string "¿No es genial?\p"
	.string "(...){PAUSE 0x24}(...){PAUSE 0x24}(...){PAUSE 0x24}\p"
	.string "Y hablando de cosas geniales...\p"
	.string "$"

gText_Cope_Pokemon::
	.string "Te presento a Tile, mi fiel compañero.\p"
	.string "Nosotros dos funcionamos igual\n"
	.string "que un sprite con su paleta.\p"
	.string "Si hay armonía entre colores y sin\n"
	.string "jaggies a la vista, no hay quien nos\l"
	.string "pare.\p"
	.string "$"

gText_Cope_ExplainChalenge::
	.string "Eso es lo que vas a tener que hacer tú.\p"
	.string "(...)(...)(...)\p"
	.string "¡No me mires así! Tranquilo, que no vas\n"
	.string "a necesitar memorizar offsets.\p"
	.string "Es muy sencillo: Se te otorgará un\n"
	.string "equipo y deberás llegar a la\l"
	.string "cima con él.\p"
	.string "Supera los errores y los jaggies\n"
	.string "que aparezcan en el camino.\p"
	.string "Si lo consigues, la puerta hacia la\n"
	.string "siguiente sala se abrirá.\l"
	.string "Prometido.\p"
	.string "Solo puedo desearte mucha suerte.\p"
	.string "Espero que nos des un buen espectáculo\n"
	.string "y llegues a la cima; ten en cuenta que\l"
	.string "este desafío no se lo pierden ni\l"
	.string "desde el más allá.\p"
	.string "Si no... bueno, siempre puedes culpar\n"
	.string "al RNG.\p"
	.string "¡Venga, que la torre no se va a\n"
	.string "subir sola!$"

gText_Birch_AndYouAre::
	.string "¿Tú quién eres?$"

gText_Birch_BoyOrGirl::
	.string "¿Eres un chico o una chica?$"

gText_Birch_WhatsYourName::
	.string "Muy bien.\n"
	.string "¿Y cómo te llamas?$"

gText_Birch_SoItsPlayer::
	.string "Así que eres {PLAYER}{KUN}…$"

gText_Birch_YourePlayer::
	.string "¡Ah, sí, ya me acuerdo!\p"
	.string "Tú te acabas de mudar a mi\n"
	.string "pueblo natal, VILLA RAÍZ.\l"
	.string "¿A que sí?\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Vale, escucha bien lo que te\n"
	.string "voy a decir…\p"
	.string "Tu propia aventura está a punto\n"
	.string "de comenzar.\p"
	.string "Adelante, entra en el mundo de los\n"
	.string "POKéMON: un mundo de ensueño, lleno\l"
	.string "de aventuras y grandes amigos.\p"
	.string "Bueno, ven a verme luego. Te espero\n"
	.string "en mi LABORATORIO POKéMON.\p"
	.string "$"
