gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} of {STR_VAR_2}$"

gContestPaintingContest::
	.string "CONTEST$"

gContestRankNormal::
	.string "NORMAL RANK$"

gContestRankSuper::
	.string "SUPER RANK$"

gContestRankHyper::
	.string "HYPER RANK$"

gContestRankMaster::
	.string "MASTER RANK$"

gContestLink::
	.string "LINK$"

gContestCoolness::
	.string "COOL$"

gContestBeauty::
	.string "BEAUTY$"

gContestCuteness::
	.string "CUTE$"

gContestSmartness::
	.string "SMART$"

gContestToughness::
	.string "TOUGH$"

gContestPaintingCool1::
	.string "The magnificent, unstoppable\n"
	.string "and super cool {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Here it is!\n"
	.string "the gorgeous {STR_VAR_1}$"

gContestPaintingCool3::
	.string "The wonderful, fantastic, and\n"
	.string "amazing {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "The most beautiful of this century:\n"
	.string "the beautiful {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "The dazzling, radiant\n"
	.string "smile of {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "The incomparable, the superstar \n"
	.string "of the POKéMON CENTER, {STR_VAR_1}$"

gContestPaintingCute1::
	.string "the loving and sweet {STR_VAR_1}$"

gContestPaintingCute2::
	.string "The winning portrait\n"
	.string "of the cute {STR_VAR_1}$"

gContestPaintingCute3::
	.string "Give us a smile!\n"
	.string "The adorable {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "The master of wit:\n"
	.string "the wise {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "The greatest among POKéMON:\n"
	.string "the unmatched {STR_VAR_1}$"

gContestPaintingSmart3::
	.string "The moment of glory\n"
	.string "of the excellent {STR_VAR_1}$"

gContestPaintingTough1::
	.string "The dizzying and\n"
	.string "super-muscular {STR_VAR_1}$"

gContestPaintingTough2::
	.string "The strong, very strong, and\n"
	.string "the mighty {STR_VAR_1}$"

gContestPaintingTough3::
	.string "The incredibly tough\n"
	.string "and amazing {STR_VAR_1}$"
