gText_AppealNumWhichMoveWillBePlayed::
	.string "Appeal No. {STR_VAR_1}!\n"
	.string "Which move will you use?$"

gText_AppealNumButItCantParticipate::
	.string "Appeal No. {STR_VAR_1}!\n"
	.string "But it can't participate!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} appeals\n"
	.string "with {STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} was\n"
	.string "watching the others.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "The appeal time\n"
	.string "is over!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"


gText_BecameMoreConsciousOfOtherMons::
	.string "It's more attentive to\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} can't\n"
	.string "appeal again.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "It settled down\n"
	.string "just a little.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "It became oblivious\n"
	.string "to the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "It became less aware\n"
	.string "of the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "It stopped caring\n"
	.string "about the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "It tried to startle\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "It tried to dazzle\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "The JUDGE looked away\n"
	.string "from {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "It tried to unnerve\n"
	.string "the next POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} became\n"
	.string "nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "It tried to unsettle\n"
	.string "the waiting POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "It taunted those\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} regained\n"
	.string "its form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "It tried to inhibit those who\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "{STR_VAR_1}, already leading,\n"
	.string "stood out even more.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "The overlooked {STR_VAR_1}\n"
	.string "worked really hard.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "It tried as hard as\n"
	.string "the preceding POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "didn't work well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "It tried just as hard as\n"
	.string "the preceding POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "didn't work well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1}'s appeal\n"
	.string "didn't work well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "worked somewhat.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "worked quite well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1}'s appeal\n"
	.string "worked wonderfully.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1}'s appeal\n"
	.string "was a total dud.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "didn't work very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "worked somewhat.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "worked quite well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "worked very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "worked wonderfully.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "It's the same type as the\n"
	.string "previous POKéMON. Nice!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "It's a different type from the\n"
	.string "previous POKéMON. Nice!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "It went over much better than\n"
	.string "the preceding POKéMON's.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "It didn't go over as well as\n"
	.string "the preceding POKéMON's.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1}'s condition\n"
	.string "rose above the usual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "A great appeal thanks\n"
	.string "to {STR_VAR_1}'s condition!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "It will appeal earlier\n"
	.string "on the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "It will appeal later\n"
	.string "on the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "It scrambled the order\n"
	.string "of the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "The JUDGE looked at {STR_VAR_1}\n"
	.string "expectantly.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
	.string "The appeal combo\n"
	.string "worked well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
	.string "The appeal combo\n"
	.string "worked very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
	.string "The appeal combo\n"
	.string "worked wonderfully.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} managed to\n"
	.string "avert its gaze.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} managed to\n"
	.string "avoid seeing it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "That didn't affect\n"
	.string "{STR_VAR_1} at all.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} got distracted\n"
	.string "just a little.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "It tried to startle\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} looked\n"
	.string "down, distracted.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} turned around,\n"
	.string "distracted.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} couldn't\n"
	.string "help crying out.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} couldn't\n"
	.string "help leaping up.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1}, distracted,\n"
	.string "tripped and fell.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} was too\n"
	.string "nervous to move.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "But it got confused.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "But it couldn't make\n"
	.string "its rival nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "But it couldn't make\n"
	.string "anyone nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
	.string "But it was ignored.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "But it couldn't improve\n"
	.string "its form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Its appeal was poor\n"
	.string "due to its poor condition.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} was left\n"
	.string "unaffected.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} disappointed\n"
	.string "by repeating its appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_3} of\n"
	.string "{STR_VAR_1} was amazing.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_3} of\n"
	.string "{STR_VAR_1} didn't work.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_3}'s\n"
	.string "{STR_VAR_1} was a huge hit!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} can't appeal on\n"
	.string "the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "It drew the attention\n"
	.string "of the crowd.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "The crowd is still\n"
	.string "watching {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_2} of\n"
	.string "{STR_VAR_1} was ignored.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
	.string "shyness$"

gText_Contest_Anxiety::
	.string "anxiety$"

gText_Contest_Laziness::
	.string "laziness$"

gText_Contest_Hesitancy::
	.string "undecided$"

gText_Contest_Fear::
	.string "fear$"
