@ Starting from here, these movements are considered
@ 'safe' (won't put follower into a Pokeball)
Common_Movement_FollowerSafeStart::
Common_Movement_QuestionMark:
	emote_question_mark
	step_end

Common_Movement_ExclamationMark:
	emote_exclamation_mark
	step_end

Common_Movement_ExclamationMarkWithDelay48:
	emote_exclamation_mark
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_DoubleExclamationMark:
	emote_double_exclamation_mark
	step_end

Common_Movement_DoubleExclamationMarkWithDelay48:
	emote_double_exclamation_mark
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_QuestionMarkWithDelay48:
	emote_question_mark
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Delay48:
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_FacePlayer:
	face_player
	step_end

Common_Movement_FaceAwayPlayer:
	face_away_player
	step_end

Common_Movement_FaceOriginalDirection:
	face_original_direction
	step_end

Common_Movement_WalkInPlaceFasterLeft:
	walk_in_place_faster_left
	step_end

Common_Movement_WalkInPlaceFasterUp:
	walk_in_place_faster_up
	step_end

Common_Movement_WalkInPlaceFasterRight:
	walk_in_place_faster_right
	step_end

Common_Movement_WalkInPlaceFasterDown:
	walk_in_place_faster_down
	step_end

Common_Movement_FaceRight::
	face_right
	step_end

Common_Movement_FaceLeft::
	face_left
	step_end

Common_Movement_FaceDown::
	face_down
	step_end

Common_Movement_FaceUp::
	face_up
	step_end

Common_Movement_WalkInPlaceDown:
	walk_in_place_down
	step_end

Common_Movement_WalkInPlaceLeft:
	walk_in_place_left
	step_end

Common_Movement_WalkInPlaceRight:
	walk_in_place_right
	step_end

Common_Movement_WalkInPlaceRight2:
	walk_in_place_right
	walk_in_place_right
	step_end

Common_Movement_WalkInPlaceUp:
	walk_in_place_up
	step_end

@ End of follower-safe movements
Common_Movement_FollowerSafeEnd::
	step_end

Common_Movement_Delay32:
	delay_16
	delay_16
	step_end

Common_Movement_WalkUp::
	walk_up
	step_end

Common_Movement_WalkUp2::
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp3::
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp4:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp5:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp6:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

@ Follower NPC
Common_Movement_WalkUpSlow::
    walk_slow_up
    step_end

Common_Movement_WalkDownSlow::
    walk_slow_down
    step_end

Common_Movement_WalkRightSlow::
    walk_slow_right
    step_end

Common_Movement_WalkLeftSlow::
    walk_slow_left
    step_end

Common_Movement_WalkDown::
    walk_down
    step_end

Common_Movement_WalkDown2::
    walk_down
	walk_down
    step_end

Common_Movement_WalkDown3:
	walk_down
	walk_down
	walk_down
    step_end

Common_Movement_WalkDown4::
    walk_down
	walk_down
	walk_down
	walk_down
    step_end

Common_Movement_WalkDown5::
    walk_down
	walk_down
	walk_down
	walk_down
	walk_down
    step_end

Common_Movement_WalkDown6::
    walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
    step_end

Common_Movement_WalkRight::
    walk_right
    step_end

Common_Movement_WalkRight2:
	walk_right
	walk_right
	step_end

Common_Movement_WalkRight3:
	walk_right
	walk_right
	walk_right
	step_end

Common_Movement_WalkRight4:
	walk_right
	walk_right
	walk_right
	walk_right
	step_end


Common_Movement_WalkLeft::
    walk_left
    step_end

Common_Movement_WalkLeft2:
    walk_left
	walk_left
    step_end

Common_Movement_WalkLeft3:
    walk_left
	walk_left
	walk_left
    step_end

Common_Movement_WalkLeft4:
    walk_left
	walk_left
	walk_left
	walk_left
    step_end

Common_Movement_WalkLeft5:
    walk_left
	walk_left
	walk_left
	walk_left
	walk_left
    step_end

Common_Movement_WalkLeft6:
    walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
    step_end

Common_Movement_WalkLeft7:
    walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
    step_end

Common_Movement_WalkLeft8:
    walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
    step_end

Common_Movement_WalkUpFast::
    walk_fast_up
    step_end

Common_Movement_WalkDownFast::
    walk_fast_down
    step_end

Common_Movement_WalkRightFast::
    walk_fast_right
    step_end

Common_Movement_WalkLeftFast::
    walk_fast_left
    step_end

Common_Movement_WalkUpFaster::
    walk_faster_up
    step_end

Common_Movement_WalkDownFaster::
    walk_faster_down
    step_end

Common_Movement_WalkRightFaster::
    walk_faster_right
    step_end

Common_Movement_WalkLeftFaster::
    walk_faster_left
    step_end


Common_Movement_JumpInPlaceDown:
	jump_in_place_down
	step_end

Common_Movement_JumpInPlaceDown2:
	jump_in_place_down
	jump_in_place_down
	step_end

Common_Movement_JumpInPlaceLeft:
	jump_in_place_left
	step_end

Common_Movement_JumpInPlaceLeft2:
	jump_in_place_left
	jump_in_place_left
	step_end

Common_Movement_JumpInPlaceLeftRight:
	jump_in_place_left_right
	step_end

Common_Movement_JumpInPlaceRight:
	jump_in_place_right
	step_end

Common_Movement_JumpInPlaceRight2:
	jump_in_place_right
	jump_in_place_right
	step_end

Common_Movement_JumpInPlaceUp:
	jump_in_place_up
	step_end

Common_Movement_JumpInPlaceUp2:
	jump_in_place_up
	jump_in_place_up
	step_end

Common_Movement_SweatDrop:
	emote_sweat_drop
	step_end

Common_Movement_SweatDropWithDelay48:
	emote_sweat_drop
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Thinking:
	emote_thinking
	step_end


Common_Movement_ThinkingWithDelay48:
	emote_thinking
	delay_16
	delay_16
	delay_16
	step_end


Common_Movement_Versus:
	emote_versus
	step_end

Common_Movement_VersusWithDelay48:
	emote_versus
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Happy:
	emote_happy
	step_end

Common_Movement_HappyWithDelay48:
        emote_happy
        delay_16
        delay_16
        delay_16
        step_end

Common_Movement_Annoyed:
        emote_annoyed
        step_end

Common_Movement_AnnoyedWithDelay48:
        emote_annoyed
        delay_16
        delay_16
        delay_16
        step_end

Common_Movement_Wink:
        emote_wink
        step_end

Common_Movement_WinkWithDelay48:
	emote_wink
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Sad:
	emote_sad
	step_end

Common_Movement_SadWithDelay48:
	emote_sad
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Smile:
	emote_smile
	step_end

Common_Movement_SmileWithDelay48:
	emote_smile
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Angry:
	emote_angry
	step_end

Common_Movement_AngryWithDelay48:
	emote_angry
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_X:
	emote_x
	step_end

Common_Movement_XWithDelay48:
	emote_x
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_V:
	emote_v
	step_end

Common_Movement_VWithDelay48:
        emote_v
        delay_16
        delay_16
        delay_16
        step_end

Common_Movement_Idea:
        emote_idea
        step_end

Common_Movement_IdeaWithDelay48:
        emote_idea
        delay_16
        delay_16
        delay_16
        step_end

Common_Movement_XD:
        emote_xd
        step_end

Common_Movement_XDWithDelay48:
        emote_xd
        delay_16
        delay_16
        delay_16
        step_end

Common_Movement_Surprise:
        emote_surprise
        step_end

Common_Movement_SurpriseWithDelay48:
	emote_surprise
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Cry:
	emote_cry
	step_end

Common_Movement_CryWithDelay48:
	emote_cry
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Heart:
	emote_heart
	step_end

Common_Movement_HeartWithDelay48:
	emote_heart
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_Sleeping:
	emote_sleeping
	step_end

Common_Movement_SmokeCigarette:
        smoke_cigarette
        step_end

Common_Movement_Fishing:
        fishing
        step_end

Common_Movement_CraneStartBurning:
        crane_start_burning
        step_end

Common_Movement_WalkLeftLockFacingDirection:
	lock_facing_direction
	walk_left
	unlock_facing_direction
	step_end

Common_Movement_WalkRightLockFacingDirection:
	lock_facing_direction
	walk_right
	unlock_facing_direction
	step_end

Common_Movement_WalkUpLockFacingDirection:
	lock_facing_direction
	walk_up
	unlock_facing_direction
	step_end

Common_Movement_WalkDownLockFacingDirection:
	lock_facing_direction
	walk_down
	unlock_facing_direction
	step_end

Common_Movement_JumpDownLockFacingDirection:
	lock_facing_direction
	jump_down
	unlock_facing_direction
	step_end

Common_Movement_JumpUpLockFacingDirection:
	lock_facing_direction
	jump_up
	unlock_facing_direction
	step_end
	
Common_Movement_JumpLeftLockFacingDirection:
	lock_facing_direction
	jump_left
	unlock_facing_direction
	step_end

Common_Movement_JumpDownFaceLeft:
	jump_down
	face_left
	step_end

Common_Movement_JumpDownFaceRight:
	jump_down
	face_right
	step_end

Common_Movement_JumpDown:
	jump_down
	step_end


Common_Movement_WalkDiagSouthEast:
	walk_diag_southeast
	step_end

