
#ifndef GUARD_DIRECT_CAMERA_MOVEMENT_TO_POS_H
#define GUARD_DIRECT_CAMERA_MOVEMENT_TO_POS_H


#define MAX_DIRECT_CAMERA_MOVEMENTS 50 

void DirectCameraMovementsToPos();

#endif //GUARD_DIRECT_CAMERA_MOVEMENT_TO_POS_H;
